"""add product catalog and visibility

Revision ID: 2ac8ba1ccfc7
Revises: fe4d218321b7
Create Date: 2026-08-31 17:02:46.289227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ac8ba1ccfc7'
down_revision: Union[str, Sequence[str], None] = 'fe4d218321b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
