"""add features column to product

Revision ID: 3cdff27f9496
Revises: 2ac8ba1ccfc7
Create Date: 2026-09-01 09:17:51.089307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cdff27f9496'
down_revision: Union[str, Sequence[str], None] = '2ac8ba1ccfc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('features', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'features')
    # ### end Alembic commands ###
