"""add is_deleted to product

Revision ID: 4f513d25c53f
Revises: 4ad3fcbe6696
Create Date: 2026-09-09 10:10:46.475491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f513d25c53f'
down_revision: Union[str, Sequence[str], None] = '4ad3fcbe6696'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_products_is_deleted'), 'products', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_is_deleted'), table_name='products')
    op.drop_column('products', 'is_deleted')
    # ### end Alembic commands ###
