"""add display_order to product

Revision ID: 55af4156d2cf
Revises: 4f513d25c53f
Create Date: 2026-09-10 14:43:23.665756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55af4156d2cf'
down_revision: Union[str, Sequence[str], None] = '4f513d25c53f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('display_order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'display_order')
    # ### end Alembic commands ###
