"""add product catalog_url and visibility

Revision ID: fe4d218321b7
Revises: b750ae059c43
Create Date: 2026-08-31 16:48:51.084935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe4d218321b7'
down_revision: Union[str, Sequence[str], None] = 'b750ae059c43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('catalog_url', sa.String(), nullable=True))
    op.add_column('products', sa.Column('is_visible', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_visible')
    op.drop_column('products', 'catalog_url')
    # ### end Alembic commands ###
